# Introdução {#cap-intro}

O Instituto de Pesquisa Econômica Aplicada – Ipea, desde 2016, é o responsável legal pela identificação, organização e gestão de estatísticas públicas referentes às Organizações da Sociedade Civil - OSCs por meio da plataforma digital Mapa das Organizações da Sociedade Civil -MOSC. A proposição desta plataforma digital foi definida no Decreto nº 8.726/2016, que regulamenta a Lei nº 13.019/2014, conhecida como Marco Regulatório das OSCs - MROSC, que fornece diretrizes legais para a atuação das OSCs no Brasil.

O MOSC é uma plataforma colaborativa, pública e gratuita, que centraliza informações e estudos sobre diversos temas relacionados à atuação das OSCs, como, por exemplo, a localização geográfica, recursos financeiros, força de trabalho, projetos, dentre outros. Nele, cada OSC possui uma página individual para a inserção de informações autodeclaradas, que complementam outros dados cadastrais oriundos de fontes de dados públicas, como Cadastro Nacional da Pessoa Jurídica - CNPJ, base principal do MOSC, a Relação Anual de Informações Sociais - RAIS e outras fontes de dados setoriais.

Originalmente, o Ipea atualizava a base cadastral do MOSC a cada dois anos [@pereira2021MOSC], porém, devido a avanços no fluxo de obtenção e processamento dos dados, a atualização tem sido feita mais de uma vez por ano. A fonte principal dos dados MOSC é a base de dados pública do CNPJ, disponibilizada pela Receita Federal no Brasil -RFB.

Todavia, nos dados da RFB, a Natureza Jurídica das organizações ainda não apresenta uma classificação direta que possibilite identificar OSCs, o que leva a necessidade da criação de um mecanismo para identificação indireta dessas entidades. A identificação de OSCs no Mapa é realizada com base em critérios internacionalmente preestabelecidos, que levam em consideração um conjunto de fatores: naturezas jurídicas específicas, atividades econômicas, razão social e certificações, que serão detalhados nesta publicação. Esses critérios foram discutidos em publicações do Instituto Brasileiro de Geografia e Estatística -IBGE sobre as Fundações Privadas e Associações sem Fins Lucrativos no Brasil -Fasfil, na publicação conhecida como COPNI (Classification of the Purposes of Non-Profit Institutions Serving Households) da Organização das Nações Unidas – ONU, bem como em publicações do Ipea [@lopez2018perfil; @pereira2021MOSC].

Esses critérios são sistematizados por meio de filtros de natureza jurídica, classificação de atividade econômica e busca textual nos campos de razão social, constituindo um algoritmo de identificação de OSCs. Esse algoritmo, a cada edição do MOSC, é revisado, aprimorado e sua metodologia de cálculo é divulgada seja no site do MOSC seja por meio de publicações.
